# We want to run this on Ubuntu 18.04 LTS
dist: bionic

language: java

services:
  - docker
  - mysql

# We want OpenJDK 8 to be the default, but OpenJDK 10 and 11 are also available.
# See https://docs.travis-ci.com/user/reference/bionic/#jvm-clojure-groovy-java-scala-support
jdk:
  - openjdk8

before_install:
  - docker run -d -p 1521:1521 gautamsaggar/oracle11g:v2 || echo "WARNING - Unable to start Oracle 11g"
  - docker ps
  - mysql -e 'CREATE DATABASE axon;'

install: true

cache:
  directories:
    - $HOME/.m2

# We switch JDK by setting the JAVA_HOME environment variable. All JDKs are under the same base directory.
script:
  - mvn -version
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent verify sonar:sonar -B -P ossrh -Dsonar.projectKey=AxonFramework_AxonFramework
  - JAVA_HOME=$(dirname ${JAVA_HOME})/openjdk11 mvn -version
  - JAVA_HOME=$(dirname ${JAVA_HOME})/openjdk11 mvn clean verify -B -P ossrh

notifications:
  slack:
    secure: d1HN9GBeH0e6EsHjNkPVXgBaFCYqbvjkZv9GUkpWnyjNYP5V1snSk6sO4X6ONttydgzfbElZTOfrgDzRTgWJ76iDMxAPccFPY7dmGcpw8/2TOjwP6H6yEitiiZcWR9fssTM2Li2WQtuGkwaVBhw15JNABzEsexxqXC+Cu48yUfA=

addons:
  sonarcloud:
    organization: "axonframework"
    token:
      secure: "cS6GecHod8X1EjDggVutgTQyKu1aQhCWnOz4KqDkxI7+u3HMwBLcJCxSctEhL0FhTp47tuB76ep/DyG/5clvvmMoY+05Qym/PJFh/qEL1LQhmcDQD3liNflbt5d3p1DaEWX4EPI5WyLVm3Y3lZlQWfW6WClIXrGRKfaUzrqaXU0="